name: flutter_news_app
description: Modern News Application with SEO support
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
